name: Deploy Release Artifacts
description: Executes the Maven deploy goal
inputs:
  profiles:
    description: Comma separated list of profiles to activate
    required: false
    default: ""
  revision:
    description: The version to release
    required: true
  sha1:
    description: The maven ci-friendly sha1 property to use
    required: false
    default: ""
  changelist:
    description: The maven ci-friendly changelist property to use
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Deploy Release Artifacts
      shell: bash
      run: ${{github.action_path}}/../scripts/ci-maven.sh -p "${{inputs.profiles}}" -g deploy -r "${{inputs.revision}}" -s "${{inputs.sha1}}" -c "${{inputs.changelist}}"
