name: Deploy Release Artifacts
description: Executes the Maven deploy goal
inputs:
  profiles:
    description: Comma separated list of profiles to activate
    required: false
  revision:
    description: The version to release
    required: true
  sha1:
    description: The maven ci-friendly sha1 property to use
    required: false
    default: ""
  changelist:
    description: The maven ci-friendly changelist property to use
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Deploy Release Artifacts
      uses: Best-Quality-Engineering/ci-maven-action@v1
      with:
        profiles: ${{inputs.profiles}}
        revision: ${{inputs.revision}}
        sha1: ${{inputs.sha1}}
        changelist: ${{inputs.changelist}}
        phases: clean, deploy
