name: Increment POM
description: Executes the ci:increment-pom goal
inputs:
  profiles:
    description: Comma separated list of profiles to activate
    required: false
  incrementor:
    description: The revision incrementing strategy
    required: false
    default: auto
  revision:
    description: The maven ci-friendly revision property to use
    required: true
  sha1:
    description: The maven ci-friendly sha1 property to use
    required: false
    default: "undefined"
  changelist:
    description: The maven ci-friendly changelist property to use
    required: false
    default: "undefined"
runs:
  using: composite
  steps:
    - name: Execute ci:increment-pom goal
      uses: Best-Quality-Engineering/ci-maven-action@v1
      with:
        profiles: ${{inputs.profiles}}
        system-properties: incrementor=${{inputs.incrementor}}
        revision: ${{inputs.revision}}
        sha1: ${{inputs.sha1}}
        changelist: ${{inputs.changelist}}
        goals: ci:increment-pom
