name: Replace Content
description: Executes the ci:replace-content goal
inputs:
  profiles:
    description: Comma separated list of profiles to activate
    required: false
  revision:
    description: The maven ci-friendly revision property to use
    required: true
  sha1:
    description: The maven ci-friendly sha1 property to use
    required: false
    default: ""
  changelist:
    description: The maven ci-friendly changelist property to use
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Execute ci:replace-content goal
      uses: Best-Quality-Engineering/ci-maven-action@v1
      with:
        profiles: ${{inputs.profiles}}
        revision: ${{inputs.revision}}
        sha1: ${{inputs.sha1}}
        changelist: ${{inputs.changelist}}
        goals: ci:replace-content
