name: Configure Git User
description: Configures the local git user details
inputs:
  name:
    description: The git user name
    required: false
    default: Automaton
  email:
    description: The git user email
    required: false
    default: bot@bestquality.engineering
runs:
  using: composite
  steps:
    - name: Configure local git user
      shell: bash
      run: ${{github.action_path}}/../scripts/git-user.sh -n "${{inputs.name}}" -e "${{inputs.email}}"
