name: Configure Git User
description: Configures the local git user details
inputs:
  name:
    description: The git user name
    required: false
    default: Automaton
  email:
    description: The git user email
    required: false
    default: bot@bestquality.engineering
runs:
  using: composite
  steps:
    - name: Configure local git user
      shell: bash
      run: |
        echo "Configuring git user details"
        git config --local user.name ${{inputs.name}}
        git config --local user.email ${{inputs.email}}
