name: Merge Release Branch
description: Executes the merge release branch script
inputs:
  version:
    description: The released version
    required: true
  release-branch:
    description: The name of the release branch
    required: true
  base-branch:
    description: The base branch into which the release branch will be merged
    required: false
    default: main
runs:
  using: composite
  steps:
    - name: Merge Release Branch
      shell: bash
      run: |
        echo "Committing tracked changes to ${{inputs.release-branch}}"
        git add -u
        git commit -m "Release ${{inputs.version}}"
        echo "Pushing ${{inputs.release-branch}} to origin"
        git push -u origin "${{inputs.release-branch}}"

        echo "Merging ${{inputs.release-branch}} to ${{inputs.base-branch}}"
        git fetch
        git checkout "${{inputs.base-branch}}"
        git pull origin "${{inputs.base-branch}}"
        git merge "${{inputs.release-branch}}"

        echo "Pushing ${{inputs.base-branch}} to origin"
        git push -u origin "${{inputs.base-branch}}"

        echo "Deleting ${{inputs.release-branch}} from origin"
        git push origin --delete "${{inputs.release-branch}}"
